//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSTree
    {
        public System.Guid DSTreeGUID { get; set; }
        public Nullable<System.Guid> ModGUID { get; set; }
        public string ID { get; set; }
        public string PID { get; set; }
        public string FactorName { get; set; }
        public string FactorNameCn { get; set; }
        public string Operator { get; set; }
        public string OperatorCn { get; set; }
        public string FactorValue { get; set; }
        public string FactorValueCn { get; set; }
        public string Describe { get; set; }
        public string DescribeCn { get; set; }
        public string Result { get; set; }
        public string ResultCn { get; set; }
        public Nullable<int> CoverCount { get; set; }
        public Nullable<int> ErroCount { get; set; }
    }
}
