//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSTreeExecutePlan
    {
        public System.Guid ExecutePlanGUID { get; set; }
        public Nullable<System.Guid> ModGUID { get; set; }
        public Nullable<int> PlanType { get; set; }
        public Nullable<System.DateTime> OnceDate { get; set; }
        public Nullable<System.DateTime> OnceTime { get; set; }
        public Nullable<int> FrequencyType { get; set; }
        public Nullable<int> IntervalCount { get; set; }
        public Nullable<bool> EWMonday { get; set; }
        public Nullable<bool> EWTuesday { get; set; }
        public Nullable<bool> EWWednesday { get; set; }
        public Nullable<bool> EWThrusday { get; set; }
        public Nullable<bool> EWFriday { get; set; }
        public Nullable<bool> EWSaturday { get; set; }
        public Nullable<bool> EWSunday { get; set; }
        public Nullable<int> EMEType { get; set; }
        public Nullable<int> EMEDay { get; set; }
        public Nullable<bool> RDType { get; set; }
        public Nullable<System.DateTime> RDETime { get; set; }
        public Nullable<int> RDInterval { get; set; }
        public Nullable<System.DateTime> RDBeginTime { get; set; }
        public Nullable<System.DateTime> DurBeginTime { get; set; }
        public Nullable<System.DateTime> DurEndTIme { get; set; }
        public Nullable<System.DateTime> DurEndTime { get; set; }
    }
}
