//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class DSTreeCEMap
    {
        public System.Guid CEMapGUID { get; set; }
        public Nullable<System.Guid> ModGUID { get; set; }
        [Display(Name = "英文字段名")]
        public string ECellName { get; set; }
        [Display(Name = "中文字段名")]
        public string CCellName { get; set; }
        [Display(Name = "结果因素")]
        public Nullable<bool> IsResultFactor { get; set; }
    }
}
