//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DSTreeModel
    {
        public System.Guid ModGUID { get; set; }
        [Display(Name = "模型名称")]
        public string ModName { get; set; }
        [Display(Name = "生成时间")]
        public Nullable<System.DateTime> ModGenerateTime { get; set; }
        [Display(Name = "数据源")]
        public string ModDataSource { get; set; }
        [Display(Name = "模型描述")]
        public string ModRemark { get; set; }
        [Display(Name = "是否文件数据")]
        public Nullable<bool> IsFileDataSource { get; set; }
        [Display(Name = "服务器")]
        public string ModServer { get; set; }
        [Display(Name = "数据库")]
        public string ModDataBase { get; set; }
        [Display(Name = "登录名")]
        public string ModUid { get; set; }
        [Display(Name = "数据库密码")]
        public string ModPassword { get; set; }
        [Display(Name = "执行周期")]
        public string ModCycleType { get; set; }
        [Display(Name = "执行日期")]
        public Nullable<int> ModCycleWD { get; set; }
        [Display(Name = "执行时间")]
        public Nullable<int> ModCycleDate { get; set; }
        [Display(Name = "模型状态")]
        public string ModStatus { get; set; }

        public string GetConnString()
        {
            string strconn = @"data source=" + ModServer + ";initial catalog=" + ModDataBase + ";user id=" + ModUid + ";password=" + ModPassword;
            return strconn;
        }
    }
}
